blueprints/cadastroProduto.py
from flask import Blueprint, request, jsonify, render_template, redirect, url_for, session, flash
from config import mysql
import base64
from flask_mysqldb import MySQL
import MySQLdb

cadastroProduto_blueprint = Blueprint('cadastroProduto', __name__)

# Area Administrativa
@cadastroProduto_blueprint.route('/adicionar_prod', methods=['POST'])
def adicionar_prod():
    if request.method == 'POST':
        produtos = request.form
        imagem = request.files.get('imagem')
        
        imagem_data = imagem.read()

        query = """
            INSERT INTO CAD_PRODUTO(
                PRODUTO,
                PRECO,
                DESCRICAO,
                QUANTIDADE,
                IMAGEM 
            )
            VALUES(
                %s,
                %s,
                %s,
                %s,
                %s
            );
        """

        cur = mysql.connection.cursor()
        # Execute com os parâmetros corretos
        cur.execute(query, (
            produtos['produto'],
            produtos['preco'],
            produtos['descricao'],
            produtos['quantidade'],
            imagem_data
        ))
        mysql.connection.commit()
        cur.close()

        return redirect(url_for('login.admin_cad'))
    
@cadastroProduto_blueprint.route('/admin/produtos', methods=['GET'])
def listar_produtos_admin():
    
        cur = mysql.connection.cursor()
        cur.execute("SELECT * FROM CAD_PRODUTO")
        produtos = cur.fetchall()
        cur.close()

        produtos_com_imagem = []
        for produto in produtos:
            imagem_b64 = base64.b64encode(produto[5] or b'').decode('utf-8') if produto[5] else 'fallback-image.png'
            produtos_com_imagem.append({
            "id": produto[0],
            "nome": produto[1],
            "preco": produto[2],
            "descricao": produto[3],
            "quantidade": produto[4],
            "imagem": imagem_b64,
            "ativo": produto[6]  
        })

        return produtos_com_imagem

        

@cadastroProduto_blueprint.route('/editar_produto/<int:produto_id>', methods=['GET', 'POST'])
def editar_produto(produto_id):
    cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    
    if request.method == 'GET':
        cur.execute("SELECT * FROM CAD_PRODUTO WHERE ID = %s", (produto_id,))
        produto = cur.fetchone()
        
        if not produto:
            flash('Produto não encontrado.', 'danger')
            return redirect(url_for('login.admin_cad'))        
        
        return render_template('editar_produto.html', produto=produto)

    elif request.method == 'POST':
            
            nome = request.form['produto']
            preco = request.form['preco']
            descricao = request.form['descricao']
            quantidade = request.form['quantidade']
            imagem = request.files.get('imagem')
            
            if imagem and imagem.filename !='':
                imagem_data = imagem.read()
                cur.execute("""
                    UPDATE CAD_PRODUTO 
                    SET PRODUTO = %s, PRECO = %s, DESCRICAO = %s, QUANTIDADE = %s, IMAGEM = %s
                    WHERE ID = %s
                """, (nome, preco, descricao, quantidade, imagem_data, produto_id))
            else:
                cur.execute("""
                    UPDATE CAD_PRODUTO 
                    SET produto = %s, preco = %s, descricao = %s, quantidade = %s
                    WHERE id = %s
                """, (nome, preco, descricao, quantidade, produto_id))

            mysql.connection.commit()
            flash('Produto atualizado com sucesso!', 'success')
            return redirect(url_for('login.admin_cad'))

    

@cadastroProduto_blueprint.route('/deletar_produto/<int:id>', methods=["POST"])
def deletar_produto(id):
    cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cur.execute("UPDATE CAD_PRODUTO SET ATIVO = 0 WHERE ID = %s", (id,))
    mysql.connection.commit()

    return redirect(url_for('login.admin_cad'))

@cadastroProduto_blueprint.route('/reativar_produto/<int:id>', methods=["POST"])
def reativar_produto(id):
    cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cur.execute("UPDATE CAD_PRODUTO SET ATIVO = 1 WHERE ID = %s", (id,))
    mysql.connection.commit()

    return redirect(url_for('login.admin_cad'))

# Área do Cliente #

def usuario_logado():
    usuario_id = session.get('usuario_id') 
    
    if not usuario_id:
        flash('Você precisa estar logado para adicionar ao carrinho.')
        return None
    return usuario_id
   
@cadastroProduto_blueprint.route('/produto', methods=['GET'])
def listar_produto():
      cur = mysql.connection.cursor()
      cur.execute("SELECT * FROM CAD_PRODUTO WHERE ATIVO =1")
      produto = cur.fetchall()
      cur.close()

        # Codificar a imagem em base64
      produtos_com_imagem = []
      for prod in produto:
        imagem_b64 = base64.b64encode(prod[5]).decode('utf-8')  
        produtos_com_imagem.append((*prod[:5], imagem_b64))  

      return render_template('produto.html', produtos=produtos_com_imagem)

# Adicionar item ao carrinho
@cadastroProduto_blueprint.route('/add_to_cart/<int:produto_id>', methods=['POST'])
def add_to_cart(produto_id):
    
    usuario_id = usuario_logado()
    if not usuario_id:
        return redirect(url_for('login.login'))
    
    # Verifica se o produto já está no carrinho do usuário
    cur = mysql.connection.cursor()
    cur.execute("""
        SELECT * FROM CARRINHO WHERE usuario_id = %s AND produto_id = %s
    """, (usuario_id, produto_id))
    item = cur.fetchone()

    if item:
        # Se o item já está no carrinho, incrementa a quantidade
        cur.execute("""
            UPDATE CARRINHO SET quantidade = quantidade + 1 WHERE usuario_id = %s AND produto_id = %s
        """, (usuario_id, produto_id))
    else:
        # Se o item não está no carrinho, insere um novo registro
        cur.execute("""
            INSERT INTO CARRINHO (usuario_id, produto_id, quantidade) VALUES (%s, %s, %s)
        """, (usuario_id, produto_id, 1))

    mysql.connection.commit()
    cur.close()

    flash(f'Produto foi adicionado ao carrinho com sucesso!', 'success')
    return redirect(url_for('cadastroProduto.listar_produto'))

@cadastroProduto_blueprint.route('/ver_carrinho', methods=['GET'])
def ver_carrinho():
    usuario_id = usuario_logado()
    if not usuario_id:
        return redirect(url_for('login.login'))

    cur = mysql.connection.cursor()
    cur.execute("""
        SELECT CARRINHO.produto_id, CAD_PRODUTO.PRODUTO, CAD_PRODUTO.PRECO, CARRINHO.quantidade, CAD_PRODUTO.IMAGEM 
        FROM CARRINHO 
        JOIN CAD_PRODUTO ON CARRINHO.produto_id = CAD_PRODUTO.id 
        WHERE CARRINHO.usuario_id = %s
    """, (usuario_id,))
    
    itens_carrinho = cur.fetchall()
    cur.close()

    # Calcular o total
    total = sum(float(item[2]) * int(item[3]) for item in itens_carrinho)
    
    # Preparar os produtos para renderizar no template
    produtos = []
    for item in itens_carrinho:
        imagem_b64 = base64.b64encode(item[4]).decode('utf-8')
        produtos.append({
            'id': item[0],
            'nome': item[1],
            'preco': item[2],
            'quantidade': item[3],
            'imagem': imagem_b64
        })

    return render_template('carrinho.html', carrinho=produtos, total=total)

@cadastroProduto_blueprint.route('/limpar_carrinho', methods=['POST'])
def limpar_carrinho():
    usuario_id = usuario_logado()
    if not usuario_id:
        return redirect(url_for('login.login'))
    
    cur = mysql.connection.cursor()
    cur.execute("""
            DELETE FROM CARRINHO WHERE usuario_id= %s
        """, (usuario_id,))
    mysql.connection.commit ()

    flash('Carrinho limpo com sucesso!')  # Mensagem de sucesso
    return redirect(url_for('cadastroProduto.ver_carrinho'))  # Redireciona para a página do carrinho

@cadastroProduto_blueprint.route('/atualizar_quantidade', methods=['POST'])
def atualizar_quantidade():
    data = request.get_json()
    item_id = data.get('item_id')
    nova_quantidade = data.get('nova_quantidade')

    if not item_id or not nova_quantidade:
        return jsonify({'error': 'Dados inválidos'}), 400

    usuario_id = usuario_logado()
    if not usuario_id:
        return jsonify({'error': 'Usuário não autenticado'}), 401

    cur = mysql.connection.cursor()
    cur.execute("""
        UPDATE CARRINHO
        SET quantidade = %s
        WHERE produto_id = %s AND usuario_id = %s
    """, (nova_quantidade, item_id, usuario_id))
    mysql.connection.commit()
    cur.close()

    return jsonify({'success': True})

@cadastroProduto_blueprint.route('/buscar_produto', methods=['GET'])
def buscar_produto():
    query = request.args.get('query')  
    if query:
        cur = mysql.connection.cursor()
        cur.execute("SELECT * FROM CAD_PRODUTO WHERE produto LIKE %s", ('%' + query + '%',))
        produtos = cur.fetchall()
        cur.close()
        return render_template('produto.html', produtos=produtos)
    return render_template('produto.html', produtos=[])

blueprints/cadastro_routes.py
from flask import Blueprint, request, jsonify, render_template, redirect, url_for, flash, session
from config import mysql
from datetime import datetime

cadastro_blueprint = Blueprint('cadastro', __name__)

@cadastro_blueprint.route('/criar-usuario', methods=['POST'])
def criar_usuario():
    if request.method == 'POST':
        usuario = request.form

        query = f"""
            INSERT INTO USUARIOS(
                NOME,
                EMAIL,
                SENHA,
                TELEFONE,
                SEXO,
                DATA_NASC,
                CURSO_CARGO,
                TURNO,
                TIPO
            )
            VALUES(
                '{usuario['nome']}',
                '{usuario['email']}',
                '{usuario['senha']}',
                 {usuario['telefone']},
                '{usuario['genero']}',
                '{usuario['data_nasc']}',
                '{usuario['curso_cargo']}',
                '{usuario['turno']}',
                1
            );
        """

        cur = mysql.connection.cursor()
        cur.execute(query)
        mysql.connection.commit()

        return redirect(url_for('login.login_page'))

@cadastro_blueprint.route('/minha_conta')
def minha_conta():
    usuario_id = session.get('usuario_id')
    if not usuario_id:
        flash("Você precisa estar logado para acessar esta página.")
        return redirect(url_for('login.login')) 

 
    cur = mysql.connection.cursor()
    cur.execute("""
        SELECT nome, email, telefone, sexo, data_nasc, curso_cargo, turno 
        FROM USUARIOS WHERE id = %s
    """, (usuario_id,))
    usuario = cur.fetchone()
    cur.close()

    if not usuario:
        flash("Usuário não encontrado.")
        return redirect(url_for('login.login'))
    
    telefone_formatado = f"({str(usuario[2])[:2]}) {str(usuario[2])[2:7]}-{str(usuario[2])[7:11]}" if usuario[2] else None

    usuario_data = {
        'nome': usuario[0],
        'email': usuario[1],
        'telefone': telefone_formatado,
        'sexo': usuario[3], 
        'data_nasc': usuario[4].strftime("%d/%m/%Y") if usuario[4] else None,
        'curso_cargo': usuario[5],
        'turno': usuario[6]
    }

    return render_template('profile.html', usuario=usuario_data)

@cadastro_blueprint.route('/editar_dados', methods=['GET', 'POST'])
def editar_dados():
    
    if 'usuario_id' not in session:
        return redirect(url_for('login'))

    usuario_id = session['usuario_id']
    
    cur = mysql.connection.cursor()
    cur.execute("""
        SELECT nome, email, telefone, sexo, data_nasc, curso_cargo, turno
        FROM USUARIOS WHERE id = %s
    """, (usuario_id,))
    usuario = cur.fetchone()
    cur.close()

    if request.method == 'POST':
        nome = request.form['nome']
        email = request.form['email']
        telefone = request.form['telefone']
        sexo = request.form['sexo']
        data_nasc = request.form['data_nasc']
        curso_cargo = request.form['curso_cargo']
        turno = request.form['turno']

        cur = mysql.connection.cursor()
        cur.execute("""
            UPDATE USUARIOS
            SET nome = %s, email = %s, telefone = %s, sexo = %s, data_nasc = %s, curso_cargo = %s, turno = %s
            WHERE id = %s
        """, (nome, email, telefone, sexo, data_nasc, curso_cargo, turno, usuario_id))
        mysql.connection.commit()
        cur.close()
        
        flash('Dados atualizados com sucesso!', 'success')
        return redirect(url_for('cadastro.minha_conta'))  

    return render_template('editar_conta.html', usuario=usuario)

@cadastro_blueprint.route('/contato', methods=['GET', 'POST'])
def enviar_mensagem():
    if request.method == 'POST':
        nome = request.form.get('nome')
        email = request.form.get('email')
        mensagem = request.form.get('mensagem')
        
        if not (nome and email and mensagem):
            flash('Por favor, preencha todos os campos.', 'danger')
            return render_template('contato.html')

    try:
        cur = mysql.connection.cursor()
        query = "INSERT INTO MSG_CONTATO (nome, email, mensagem) VALUES (%s, %s, %s)"
        valores = (nome, email, mensagem)
        cur.execute(query, valores)
        mysql.connection.commit()
        cur.close()

        flash('Mensagem enviada com sucesso!', 'success')
        return redirect(url_for('cadastro.enviar_mensagem'))
        
    except Exception as e:
            flash('')
            return render_template('contato.html')


@cadastro_blueprint.route('/exibir_mensagens', methods=['GET'])
def exibir_mensagens():
    cur = mysql.connection.cursor()
    cur.execute("SELECT id, nome, email, mensagem, data_envio FROM MSG_CONTATO ORDER BY data_envio DESC")
    mensagens = cur.fetchall()
    cur.close()
    
    return mensagens

blueprints/login_routes.py
from flask import Blueprint, flash, request, jsonify, render_template, redirect, url_for, session, make_response
from config import db
import base64
from blueprints.pedidos import listar_pedidos
from blueprints.cadastroProduto import listar_produtos_admin
from blueprints.cadastro_routes import exibir_mensagens

login_blueprint = Blueprint('login', __name__)


@login_blueprint.route('/', methods=['GET'])
def home():
    return redirect(url_for('login.login_page'))

@login_blueprint.route('/login', methods=['GET'])
def login_page():
    return render_template('login.html')

@login_blueprint.route('/read_login_form', methods=['GET', 'POST'])
def read_login_form():
    if request.method == 'POST':
        return redirect(url_for('login.index'))
    
    return render_template('index.html')

@login_blueprint.route('/index', methods=['GET'])
def index():
    return render_template('index.html')

@login_blueprint.route('/cadastro', methods=['GET'])
def cadastro():
    return render_template('cadastro.html')

@login_blueprint.route('/login', methods=['POST'])
def login1():
    
      email = request.form['email']
      senha = request.form['senha']

    # Consultando o banco de dados   
      cursor = db.cursor(dictionary=True)
      cursor.execute('select * from USUARIOS WHERE email = %s AND senha = %s', (email, senha))
      usuario = cursor.fetchone()

     # Verificando se o usuário existe
      if usuario:
        session['usuario_id'] = usuario ['ID']
        session['usuario_logado'] = True
        if usuario['TIPO'] == 0:  
                return redirect(url_for('login.admin_cad'))  # Redireciona para página de admin
        else:
            return redirect(url_for('cadastroProduto.listar_produto'))
      else:
        flash('Credenciais inválidas. Tente novamente.', 'danger')
        return redirect(url_for('login.home'))  


@login_blueprint.route('/admin_cad', methods=['GET'])
def admin_cad():
       
    produtos= listar_produtos_admin()
    pedidos = listar_pedidos()
    mensagens = exibir_mensagens()

    return render_template('areaADM.html', produtos=produtos, pedidos=pedidos, mensagens=mensagens)  

@login_blueprint.route('/logout')
def logout():
    session.clear()
    flash('Você saiu da sua conta com sucesso.', 'success')
    return redirect(url_for('login.login_page'))

templates/areaADM.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Área do Administrador</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nerko+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style-cadProduto.css') }}" type="text/css">
    <link rel="icon" href="{{ url_for('static', filename='images/cupcake.png') }}" type="image/png">
</head>
<body>
    <div>  
             
        <!-- Barra de navegação -->
        <div class="nav-buttons">
            <a href="javascript:void(0)" onclick="loadSection('listar-produtos')" class="nav-button">Listar Produtos</a>
            <a href="javascript:void(0)" onclick="loadSection('cadastrar-produto')" class="nav-button">Cadastrar Produto</a>
            <a href="javascript:void(0)" onclick="loadSection('listar-pedidos')" class="nav-button">Listar Pedidos</a>
            <a href="javascript:void(0)" onclick="loadSection('exibir-mensagens')" class="nav-button">Exibir Mensagens</a>
        </div>
        
        
        <!-- LISTAR PRODUTOS -->
<div id="listar-produtos" class="content-section">
    <h2>Produtos Cadastrados</h2>
    <div class="product-list">
            <table class="no-borders">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Imagem</th>
                        <th>Nome</th>
                        <th>Preço</th>
                        <th>Quantidade</th>
                        <th>Descrição</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
        {% if produtos %}
        {% for produto in produtos %}
        <tr>
            <td>{{ produto['id'] }}</td> 
            <td><img src="data:image/png;base64,{{ produto['imagem'] }}" alt="Doce" class="imagem-doce"></td> 
            <td>{{ produto['nome'] }}</td> 
            <td>R$ {{ produto['preco'] }}</td> 
            <td>{{ produto['quantidade'] }}</td> 
            <td class="descricao">{{ produto['descricao'] }}</td> 
            <td class="acoes">
                <a href="{{ url_for('cadastroProduto.editar_produto', produto_id=produto['id']) }}" class="btn btn-warning">Editar</a>
                {% if produto['ativo'] == 1 %}
                    <form action="{{ url_for('cadastroProduto.deletar_produto', id=produto['id']) }}" method="POST" onsubmit="return confirm('Tem certeza que deseja excluir este produto?')">
                        <button type="submit" class="btn-excluir">Excluir</button>
                    </form>
                {% else %}
                    <form action="{{ url_for('cadastroProduto.reativar_produto', id=produto['id']) }}" method="POST">
                        <button type="submit" class="btn btn-success">Reativar</button>
                    </form>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    
    {% else %}
        <tr>
            <td colspan="7">Nenhum produto encontrado.</td>
        </tr>
    {% endif %}
</tbody>
</table>
</div>
</div>


<!-- CADASTRAR PRODUTO -->
<div id="cadastrar-produto" class="content-section">
    <h2>Cadastro de Produto</h2>
    <form action="{{ url_for('cadastroProduto.adicionar_prod') }}" method="post" enctype="multipart/form-data">
        <label for="produto">Nome do Produto:</label><br>
        <input type="text" id="produto" name="produto" required><br><br>
        <label for="preco">Preço:</label><br>
        <input type="number" id="preco" name="preco" step="0.01" required><br><br>
        <label for="descricao">Descrição:</label><br>
        <textarea id="descricao" name="descricao" required></textarea><br><br>
        <label for="quantidade">Quantidade em Estoque:</label><br>
        <input type="number" id="quantidade" name="quantidade" required><br><br>
        <label for="imagem">Imagem:</label><br>
        <input type="file" id="imagem" name="imagem" accept="image/*" required><br><br>
        <input type="submit" value="Cadastrar Produto">
    </form>
</div>

<!-- LISTAR PEDIDOS -->
<div id="listar-pedidos" class="content-section">
    <h1>Pedidos Realizados</h1>
    <table>
        <thead>
            <tr>
            <th>Pedido ID</th>
            <th>Cliente</th>
            <th>Data</th>
            <th>Itens</th>           
            <th>Forma de Pagamento</th>
            <th>Total</th>
            <th>Status</th>
                
            </tr>
        </thead>
        <tbody>
            {% for pedido in pedidos %}
                <tr>
                    <td>{{ pedido.id }}</td>
                    <td>{{ pedido.nome_cliente}}</td>
                    <td>{{ pedido.order_date.strftime('%d/%m/%Y') }}</td>   
                    <td>
                        <ul>
                            {% for item in pedido.itens %}
                            <li> <b>{{ item['nome_produto'] }}</b> <br> Quantidade: <b>{{ item['quantidade'] }} </b> <br>Preço: <b>{{ item['preco'] }}</b></li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{ pedido.forma_pagamento or 'Não Informada' }}</td>
                    <td>R$ {{ pedido.total }}</td>
                    <td>{{ pedido.status }}
                    
                        <form action="{{ url_for('pedidos.atualizar_status', pedido_id=pedido.id) }}" method="POST">
                            {% if pedido.status != 'Concluído' %}
                                <button type="submit" class="btn btn-success">Marcar como Concluído</button>
                            {% else %}
                                <button type="button" class="btn btn-disabled" disabled>Concluído</button>
                            {% endif %}
                        </form>                        
                    </td>
                </tr>
            {% endfor %}
        </tbody>  
    </table>
</div>
<!-- EXIBIR MENSAGENS -->
<div id="exibir-mensagens" class="content-section">
    <h2>Mensagens Recebidas</h2>
    <table class="no-borders">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Mensagem</th>
                <th>Data</th>
            </tr>
        </thead>
        <tbody>
            {% if mensagens %}
            {% for mensagem in mensagens %}
                <tr>
                    <td>{{ mensagem[0] }}</td>
                    <td>{{ mensagem[1] }}</td>
                    <td>{{ mensagem[2] }}</td>
                    <td>{{ mensagem[3] }}</td>
                    <td>{{ mensagem[4] }}</td>
                </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="5">Nenhuma mensagem encontrada.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>

    <script>
        function loadSection(sectionId) {
            const sections = document.querySelectorAll('.content-section');
            sections.forEach(section => {
                section.style.display = 'none';
            });
            
            const activeSection = document.getElementById(sectionId);
            if (activeSection) {
                activeSection.style.display = 'block';
            }
        }
    
        document.addEventListener('DOMContentLoaded', function () {
            loadSection('listar-produtos');  
        });
    </script>
    
</body>
</html>

templates/cadastroProduto.html
        <!DOCTYPE html>
        <html lang="pt-br">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Cadastro de Produtos</title>
            <link rel="preconnect" href="https://fonts.googleapis.com">
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
            <link href="https://fonts.googleapis.com/css2?family=Nerko+One&display=swap" rel="stylesheet">
            <link rel="stylesheet" href="{{url_for('static', filename='styles/style-cadProduto.css')}}" type="text/css">
            <link rel="icon" href="{{url_for('static', filename='images/cupcake.png')}}" type="image/png">
        </head>
        <body>
            <div>
            <h1>Cadastro de Produtos</h1>
            <form action="{{url_for('cadastroProduto.listar_produto')}}" method="GET">
                <input type="submit" value="Listar produtos">
            </form>
            </div>

          <div>
            <form action="{{url_for('cadastroProduto.adicionar_prod')}}" method="post" enctype="multipart/form-data">
                <label for= "nome">Nome do Produto:</label><br>
                <input type="text" id="produto" name="produto" required><br><br>
        
                <label for="preco">Preço:</label><br>
                <input type="number" id="preco" name="preco" step="0.01" required><br><br>
        
                <label for="descricao">Descrição:</label><br>
                <textarea id="descricao" name="descricao" rows="4" required></textarea><br><br>
        
                <label for="categoria">Quantidade:</label><br>
                <input type="number" id="categoria" name="categoria" required><br><br>
        
                <!-- Adicionando o upload de imagem -->
                <label for="image">Selecione uma imagem:</label><br>
                <input type="file" name="imagem" required><br><br>
                <input type="submit" value="Cadastrar">

            </form>
        </div>
        <form action="{{url_for('pedidos.listar_pedidos')}}" method="GET">
            <input type="submit" value="Lista de Pedidos">
        </form>
        </body>
        </html>
        

templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{url_for('static', filename='images/cupcake.png')}}" type="image/png">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/barra_navegar.css')}}">
    {% block head %}{% endblock %}  
    </head>

    <body>
        <header>
        <nav class="navbar">
            <div class="logo">Doce Impacto</div>
            <div class="menu">
                <a href="{{ url_for('cadastroProduto.listar_produto')}}">Produtos</a>
                <a href="{{ url_for('feedback.feedbacks') }}">FeedBacks</a> 
                <a href="{{ url_for('cadastro.enviar_mensagem') }}">Contato</a>
                <a href="{{ url_for('cadastroProduto.ver_carrinho') }}"><img src="{{url_for('static', filename='images/carrinho.png')}}"alt="Carro"> Carrinho</a>
    
                {% if session.get('usuario_logado') %}
                    <a href="{{ url_for('cadastro.minha_conta') }}">Minha Conta</a>
                {% else %}
                    <a href="{{ url_for('login.login1') }}">Login</a>
                {% endif %}
                
                <a href="javascript:void(0);" id="search-icon">
                    <img src="{{ url_for('static', filename='images/lupa.png') }}" alt="Buscar">
                </a>
                <div id="search-box" class="search-box" style="display:none;">
                    <header class="search">
                        <form action="{{ url_for('cadastroProduto.buscar_produto') }}" method="GET" id="search-form">
                            <input type="text" id="search-input" name="query" placeholder="Digite o nome do produto" onkeypress="handleEnter(event)">
                            <i class="bx bx-search-alt-2" onclick="submitSearch()"></i> <!-- Ícone de busca -->
                        </form>
                    </header>
                </div>
            </div>
        </nav>
    </header>
    
    <main>
        {% block content %}{% endblock %}
    </main>
</body>
<footer>
    <p>&copy; 2024 Doce Impacto. Todos os direitos reservados.</p>
</footer>
</html>

<script>
    let lastScroll = 0;
    const navbar = document.querySelector('.navbar'); 

    window.addEventListener('scroll', () => {
        const currentScroll = window.pageYOffset;
        if (currentScroll > lastScroll) {
           
            navbar.classList.add('navbar-hidden');
        } else {
            
            navbar.classList.remove('navbar-hidden');
        }
        lastScroll = currentScroll;
    });
    document.getElementById('search-icon').onclick = function() {
    var searchBox = document.getElementById('search-box');
    if (searchBox.style.display === 'none' || searchBox.style.display === '') {
        searchBox.style.display = 'flex'; 
    } else {
        searchBox.style.display = 'none'; 
    }
}
function handleEnter(event) {
    if (event.key === 'Enter') {
        event.preventDefault();  
        submitSearch();          
    }
}
function submitSearch() {
    const searchInput = document.getElementById('search-input').value;
    if (searchInput) {
        
        document.getElementById('search-form').submit();
    }
}
</script>